# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Sat Apr 20 00:37:39 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 474)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_archive_button = QtWidgets.QPushButton(self.centralWidget)
        self.open_archive_button.setText("")
        self.open_archive_button.setObjectName("open_archive_button")
        self.horizontalLayout.addWidget(self.open_archive_button)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.save_pdf_button = QtWidgets.QPushButton(self.centralWidget)
        self.save_pdf_button.setText("")
        self.save_pdf_button.setObjectName("save_pdf_button")
        self.horizontalLayout.addWidget(self.save_pdf_button)
        self.stop_proc_button = QtWidgets.QPushButton(self.centralWidget)
        self.stop_proc_button.setText("")
        self.stop_proc_button.setObjectName("stop_proc_button")
        self.horizontalLayout.addWidget(self.stop_proc_button)
        self.save_word_button = QtWidgets.QPushButton(self.centralWidget)
        self.save_word_button.setText("")
        self.save_word_button.setObjectName("save_word_button")
        self.horizontalLayout.addWidget(self.save_word_button)
        self.save_button = QtWidgets.QPushButton(self.centralWidget)
        self.save_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setStyleSheet("")
        self.save_button.setText("")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.select_folder_button = QtWidgets.QPushButton(self.centralWidget)
        self.select_folder_button.setText("")
        self.select_folder_button.setObjectName("select_folder_button")
        self.horizontalLayout.addWidget(self.select_folder_button)
        self.proc_button = QtWidgets.QPushButton(self.centralWidget)
        self.proc_button.setStyleSheet("")
        self.proc_button.setText("")
        self.proc_button.setObjectName("proc_button")
        self.horizontalLayout.addWidget(self.proc_button)
        self.split_pages_button = QtWidgets.QPushButton(self.centralWidget)
        self.split_pages_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.split_pages_button.sizePolicy().hasHeightForWidth())
        self.split_pages_button.setSizePolicy(sizePolicy)
        self.split_pages_button.setMinimumSize(QtCore.QSize(0, 0))
        self.split_pages_button.setBaseSize(QtCore.QSize(0, 0))
        self.split_pages_button.setText("")
        self.split_pages_button.setObjectName("split_pages_button")
        self.horizontalLayout.addWidget(self.split_pages_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextEdit(self.centralWidget)
        self.textBrowser.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Panel)
        self.textBrowser.setMidLineWidth(3)
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.spinner_widget = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinner_widget.sizePolicy().hasHeightForWidth())
        self.spinner_widget.setSizePolicy(sizePolicy)
        self.spinner_widget.setStyleSheet("background-color: rgba(255, 255, 255, 255);\n"
"/*border: 1px solid silver; */")
        self.spinner_widget.setFrameShape(QtWidgets.QFrame.Panel)
        self.spinner_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.spinner_widget.setMidLineWidth(3)
        self.spinner_widget.setText("")
        self.spinner_widget.setObjectName("spinner_widget")
        self.verticalLayout_3.addWidget(self.spinner_widget)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 255);\n"
"border-color: rgb(193, 0, 0);\n"
"/* border-radius: 4px;\n"
"border: 4px; */")
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setMidLineWidth(3)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.imgScrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.imgScrollArea.setStyleSheet("/*border: 1px solid transparent; */\n"
"background-color: rgba(255, 255, 255, 255);")
        self.imgScrollArea.setFrameShape(QtWidgets.QFrame.Panel)
        self.imgScrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imgScrollArea.setLineWidth(1)
        self.imgScrollArea.setMidLineWidth(3)
        self.imgScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.imgScrollArea.setWidgetResizable(True)
        self.imgScrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.imgScrollArea.setObjectName("imgScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 344, 298))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.imgScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.imgScrollArea)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 5, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.prev_button = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_button.sizePolicy().hasHeightForWidth())
        self.prev_button.setSizePolicy(sizePolicy)
        self.prev_button.setText("")
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout_5.addWidget(self.prev_button)
        self.curr_pic_label = QtWidgets.QLabel(self.centralWidget)
        self.curr_pic_label.setText("")
        self.curr_pic_label.setObjectName("curr_pic_label")
        self.horizontalLayout_5.addWidget(self.curr_pic_label)
        self.next_button = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setText("")
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_5.addWidget(self.next_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Urdu Optical Character Recognition", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))

